# One Area 1960 Models ----------------------------------------------------
onearea_1960 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_starta/mle_report.RDS")
onearea_1960_noinit <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_no_inita/mle_report.RDS")
onearea_1960_noinit_10 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_dont_est_10a/mle_report.RDS")
onearea_1960_noinit_sr <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_SRa/mle_report.RDS")
onearea_1960_noinit_sum0 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_sum_zero_recruita/mle_report.RDS")
onearea_1960_noinit_tagP_10 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_include_tag_dataa/mle_report.RDS")
onearea_1960_noinit_tagP <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_pois_est_all_ycsa/mle_report.RDS")
onearea_1960_noinit_tagNB <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_negative_binomiala/mle_report.RDS")
onearea_1960_noinit_tagNB_decadal <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960decadal_tag_reporta/mle_report.RDS")
onearea_1960_noinit_DM_comp <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1960_DM_comp_likelihoodsa/mle_report.RDS")

plot(onearea_1960$sel_fixed_f[,1])
lines(onearea_1960_noinit$sel_fixed_f[,1])
lines(onearea_1960_noinit_10$sel_fixed_f[,1])
lines(onearea_1960_noinit_sr$sel_fixed_f[,1])
lines(onearea_1960_noinit_sum0$sel_fixed_f[,1])
lines(onearea_1960_noinit_tagP_10$sel_fixed_f[,1])
lines(onearea_1960_noinit_tagP$sel_fixed_f[,1])
lines(onearea_1960_noinit_tagNB$sel_fixed_f[,1])
lines(onearea_1960_noinit_tagNB_decadal$sel_fixed_f[,1])
lines(onearea_1960_noinit_DM_comp$sel_fixed_f[,1])

plot(onearea_1960$sel_fixed_f[,2])
lines(onearea_1960_noinit$sel_fixed_f[,2])
lines(onearea_1960_noinit_10$sel_fixed_f[,2])
lines(onearea_1960_noinit_sr$sel_fixed_f[,2])
lines(onearea_1960_noinit_sum0$sel_fixed_f[,2])
lines(onearea_1960_noinit_tagP_10$sel_fixed_f[,2])
lines(onearea_1960_noinit_tagP$sel_fixed_f[,2])
lines(onearea_1960_noinit_tagNB$sel_fixed_f[,2])
lines(onearea_1960_noinit_tagNB_decadal$sel_fixed_f[,2])
lines(onearea_1960_noinit_DM_comp$sel_fixed_f[,2])

plot(onearea_1960$init_rec_dev)
lines(onearea_1960_noinit$init_rec_dev)
lines(onearea_1960_noinit_10$init_rec_dev)
lines(onearea_1960_noinit_sr$init_rec_dev)
lines(onearea_1960_noinit_sum0$init_rec_dev)
lines(onearea_1960_noinit_tagP_10$init_rec_dev)
lines(onearea_1960_noinit_tagP$init_rec_dev)
lines(onearea_1960_noinit_tagNB$init_rec_dev)
lines(onearea_1960_noinit_tagNB_decadal$init_rec_dev)
lines(onearea_1960_noinit_DM_comp$init_rec_dev)

plot(onearea_1960$SSB_yr)
lines(onearea_1960_noinit$SSB_yr)
lines(onearea_1960_noinit_10$SSB_yr)
lines(onearea_1960_noinit_sr$SSB_yr)
lines(onearea_1960_noinit_sum0$SSB_yr)
lines(onearea_1960_noinit_tagP_10$SSB_yr)
lines(onearea_1960_noinit_tagP$SSB_yr)
lines(onearea_1960_noinit_tagNB$SSB_yr)
lines(onearea_1960_noinit_tagNB_decadal$SSB_yr)
lines(onearea_1960_noinit_DM_comp$SSB_yr)

plot(onearea_1960$recruitment_yr)
plot(onearea_1960_noinit$recruitment_yr)
plot(onearea_1960_noinit_10$recruitment_yr)
plot(onearea_1960_noinit_sr$recruitment_yr)
plot(onearea_1960_noinit_sum0$recruitment_yr)
plot(onearea_1960_noinit_tagP_10$recruitment_yr)
plot(onearea_1960_noinit_tagP$recruitment_yr)
plot(onearea_1960_noinit_tagNB$recruitment_yr)
plot(onearea_1960_noinit_tagNB_decadal$recruitment_yr)
plot(onearea_1960_noinit_DM_comp$recruitment_yr)


# One Area 1977 Models ----------------------------------------------------
onearea_1977 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_init_devsa/mle_report.RDS")
onearea_1977_no_init <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_starta/mle_report.RDS")
onearea_1977_sum0 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_rec_sum_zeroa/mle_report.RDS") # wrong! same model as starta
onearea_1977_DM <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_DM_comp_likelihoodsa/mle_report.RDS") 
onearea_1977_tagP <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_include_tag_dataa/mle_report.RDS") 
onearea_1977_tagNB <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_negative_binomiala/mle_report.RDS") 
onearea_1977_tagNB_decadal <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/1-Area/1977_decadal_tag_reporta/mle_report.RDS") 

plot(onearea_1977_no_init$sel_fixed_f[,1])
lines(onearea_1977$sel_fixed_f[,1])
lines(onearea_1977_sum0$sel_fixed_f[,1])
lines(onearea_1977_DM$sel_fixed_f[,1])
lines(onearea_1977_tagP$sel_fixed_f[,1])
lines(onearea_1977_tagNB$sel_fixed_f[,1])
lines(onearea_1977_tagNB_decadal$sel_fixed_f[,1])

plot(onearea_1977_no_init$sel_fixed_f[,2])
lines(onearea_1977$sel_fixed_f[,2])
lines(onearea_1977_sum0$sel_fixed_f[,2])
lines(onearea_1977_DM$sel_fixed_f[,2])
lines(onearea_1977_tagP$sel_fixed_f[,2])
lines(onearea_1977_tagNB$sel_fixed_f[,2])
lines(onearea_1977_tagNB_decadal$sel_fixed_f[,2])

plot(onearea_1977_no_init$init_rec_dev)
plot(onearea_1977$init_rec_dev)
plot(onearea_1977_sum0$init_rec_dev)
plot(onearea_1977_DM$init_rec_dev)
plot(onearea_1977_tagP$init_rec_dev)
plot(onearea_1977_tagNB$init_rec_dev)
plot(onearea_1977_tagNB_decadal$init_rec_dev)

plot(onearea_1977_no_init$natage_f[,,1])
plot(onearea_1977$natage_f[,,1])
plot(onearea_1977_sum0$natage_f[,,1])
plot(onearea_1977_DM$natage_f[,,1])
plot(onearea_1977_tagP$natage_f[,,1])
plot(onearea_1977_tagNB$natage_f[,,1])
plot(onearea_1977_tagNB_decadal$natage_f[,,1])

plot(onearea_1977_no_init$SSB_yr)
lines(onearea_1977$SSB_yr)
lines(onearea_1977_sum0$SSB_yr)
lines(onearea_1977_DM$SSB_yr)
lines(onearea_1977_tagP$SSB_yr)
lines(onearea_1977_tagNB$SSB_yr)
lines(onearea_1977_tagNB_decadal$SSB_yr)

plot(onearea_1977_no_init$recruitment_yr)
lines(onearea_1977$recruitment_yr)
lines(onearea_1977_sum0$recruitment_yr)
lines(onearea_1977_DM$recruitment_yr)
lines(onearea_1977_tagP$recruitment_yr)
lines(onearea_1977_tagNB$recruitment_yr)
lines(onearea_1977_tagNB_decadal$recruitment_yr)


# 3 Area 1960 Models ------------------------------------------------------
thrarea_1960_notag_global <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_NoTagData_srva/mle_report.RDS")
thrarea_1960_notag_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_NoTagData_regrecruit_srva/mle_report.RDS")
thrarea_1960_notag_estmov_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_NoTagData_est_move_srva/mle_report.RDS")
thrarea_1960_notag_fenske_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_fenske_movement_countrysrva/mle_report.RDS")
thrarea_1960_notag_fenske_sptq_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_fenske_movement_spatial_q_countrysrva/mle_report.RDS")
thrarea_1960_tag_estmov_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_TagData_01_srva/mle_report.RDS")
thrarea_1960_tag_estmov_regional_trwlfix <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_TagData_01_alt_srva/mle_report.RDS")
thrarea_1960_tag_estmov_regional_NB <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_TagData_02_srva/mle_report.RDS")
thrarea_1960_tag_estmov_regional_NB_decadal <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_TagData_03_srva/mle_report.RDS")
thrarea_1960_tag_estmov_regional_NB_decadal_DM <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_Model_04_srva/mle_report.RDS")
thrarea_1960_tag_estmov_regional_NB_decadal_sptq <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1960_spatial_qsa/mle_report.RDS")

plot(thrarea_1960_notag_global$sel_fixed_f[,1])
lines(thrarea_1960_notag_regional$sel_fixed_f[,1])
lines(thrarea_1960_notag_estmov_regional$sel_fixed_f[,1])
lines(thrarea_1960_notag_fenske_regional$sel_fixed_f[,1])
lines(thrarea_1960_notag_fenske_sptq_regional$sel_fixed_f[,1])
lines(thrarea_1960_tag_estmov_regional$sel_fixed_f[,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$sel_fixed_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB$sel_fixed_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$sel_fixed_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$sel_fixed_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$sel_fixed_f[,1])

plot(thrarea_1960_notag_global$sel_fixed_f[,2])
lines(thrarea_1960_notag_regional$sel_fixed_f[,2])
lines(thrarea_1960_notag_estmov_regional$sel_fixed_f[,2])
lines(thrarea_1960_notag_fenske_regional$sel_fixed_f[,2])
lines(thrarea_1960_notag_fenske_sptq_regional$sel_fixed_f[,2])
lines(thrarea_1960_tag_estmov_regional$sel_fixed_f[,2])
lines(thrarea_1960_tag_estmov_regional_trwlfix$sel_fixed_f[,2])
lines(thrarea_1960_tag_estmov_regional_NB$sel_fixed_f[,2])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$sel_fixed_f[,2])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$sel_fixed_f[,2])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$sel_fixed_f[,2])

plot(thrarea_1960_notag_global$sel_trwl_f[,1])
lines(thrarea_1960_notag_regional$sel_trwl_f[,1])
lines(thrarea_1960_notag_estmov_regional$sel_trwl_f[,1])
lines(thrarea_1960_notag_fenske_regional$sel_trwl_f[,1])
lines(thrarea_1960_notag_fenske_sptq_regional$sel_trwl_f[,1])
lines(thrarea_1960_tag_estmov_regional$sel_trwl_f[,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$sel_trwl_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB$sel_trwl_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$sel_trwl_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$sel_trwl_f[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$sel_trwl_f[,1])

plot(thrarea_1960_notag_global$sel_trwl_m[,1])
lines(thrarea_1960_notag_regional$sel_trwl_m[,1])
lines(thrarea_1960_notag_estmov_regional$sel_trwl_m[,1])
lines(thrarea_1960_notag_fenske_regional$sel_trwl_m[,1])
lines(thrarea_1960_notag_fenske_sptq_regional$sel_trwl_m[,1])
lines(thrarea_1960_tag_estmov_regional$sel_trwl_m[,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$sel_trwl_m[,1])
lines(thrarea_1960_tag_estmov_regional_NB$sel_trwl_m[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$sel_trwl_m[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$sel_trwl_m[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$sel_trwl_m[,1])

plot(thrarea_1960_notag_global$init_rec_dev)
plot(thrarea_1960_notag_regional$init_rec_dev)
plot(thrarea_1960_notag_estmov_regional$init_rec_dev)
plot(thrarea_1960_notag_fenske_regional$init_rec_dev)
plot(thrarea_1960_notag_fenske_sptq_regional$init_rec_dev)
plot(thrarea_1960_tag_estmov_regional$init_rec_dev)
plot(thrarea_1960_tag_estmov_regional_trwlfix$init_rec_dev)
plot(thrarea_1960_tag_estmov_regional_NB$init_rec_dev)
plot(thrarea_1960_tag_estmov_regional_NB_decadal$init_rec_dev)
plot(thrarea_1960_tag_estmov_regional_NB_decadal_DM$init_rec_dev)
plot(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$init_rec_dev)

plot(thrarea_1960_notag_global$natage_f[,1,1])
lines(thrarea_1960_notag_regional$natage_f[,1,1])
lines(thrarea_1960_notag_estmov_regional$natage_f[,1,1])
lines(thrarea_1960_notag_fenske_regional$natage_f[,1,1])
lines(thrarea_1960_notag_fenske_sptq_regional$natage_f[,1,1])
lines(thrarea_1960_tag_estmov_regional$natage_f[,1,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$natage_f[,1,1])
lines(thrarea_1960_tag_estmov_regional_NB$natage_f[,1,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$natage_f[,1,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$natage_f[,1,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$natage_f[,1,1])

plot(thrarea_1960_notag_global$natage_f[,2,1])
lines(thrarea_1960_notag_regional$natage_f[,2,1])
lines(thrarea_1960_notag_estmov_regional$natage_f[,2,1])
lines(thrarea_1960_notag_fenske_regional$natage_f[,2,1])
lines(thrarea_1960_notag_fenske_sptq_regional$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$natage_f[,2,1])

plot(thrarea_1960_notag_global$natage_f[,2,1])
lines(thrarea_1960_notag_regional$natage_f[,2,1])
lines(thrarea_1960_notag_estmov_regional$natage_f[,2,1])
lines(thrarea_1960_notag_fenske_regional$natage_f[,2,1])
lines(thrarea_1960_notag_fenske_sptq_regional$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$natage_f[,2,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$natage_f[,2,1])

plot(thrarea_1960_notag_global$SSB_yr[,1], ylim = c(0, 150))
lines(thrarea_1960_notag_regional$SSB_yr[,1])
lines(thrarea_1960_notag_estmov_regional$SSB_yr[,1])
lines(thrarea_1960_notag_fenske_regional$SSB_yr[,1])
lines(thrarea_1960_notag_fenske_sptq_regional$SSB_yr[,1])
lines(thrarea_1960_tag_estmov_regional$SSB_yr[,1])
lines(thrarea_1960_tag_estmov_regional_trwlfix$SSB_yr[,1])
lines(thrarea_1960_tag_estmov_regional_NB$SSB_yr[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$SSB_yr[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$SSB_yr[,1])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$SSB_yr[,1])

plot(thrarea_1960_notag_global$SSB_yr[,2], ylim = c(0, 200))
lines(thrarea_1960_notag_regional$SSB_yr[,2])
lines(thrarea_1960_notag_estmov_regional$SSB_yr[,2])
lines(thrarea_1960_notag_fenske_regional$SSB_yr[,2])
lines(thrarea_1960_notag_fenske_sptq_regional$SSB_yr[,2])
lines(thrarea_1960_tag_estmov_regional$SSB_yr[,2])
lines(thrarea_1960_tag_estmov_regional_trwlfix$SSB_yr[,2])
lines(thrarea_1960_tag_estmov_regional_NB$SSB_yr[,2])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$SSB_yr[,2])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$SSB_yr[,2])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$SSB_yr[,2])

plot(thrarea_1960_notag_global$SSB_yr[,3], ylim = c(0, 200))
lines(thrarea_1960_notag_regional$SSB_yr[,3])
lines(thrarea_1960_notag_estmov_regional$SSB_yr[,3])
lines(thrarea_1960_notag_fenske_regional$SSB_yr[,3])
lines(thrarea_1960_notag_fenske_sptq_regional$SSB_yr[,3])
lines(thrarea_1960_tag_estmov_regional$SSB_yr[,3])
lines(thrarea_1960_tag_estmov_regional_trwlfix$SSB_yr[,3])
lines(thrarea_1960_tag_estmov_regional_NB$SSB_yr[,3])
lines(thrarea_1960_tag_estmov_regional_NB_decadal$SSB_yr[,3])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_DM$SSB_yr[,3])
lines(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$SSB_yr[,3])

plot(thrarea_1960_notag_global$recruitment_yr[,1])
plot(thrarea_1960_notag_regional$recruitment_yr[,1])
plot(thrarea_1960_notag_estmov_regional$recruitment_yr[,1])
plot(thrarea_1960_notag_fenske_regional$recruitment_yr[,1])
plot(thrarea_1960_notag_fenske_sptq_regional$recruitment_yr[,1])
plot(thrarea_1960_tag_estmov_regional$recruitment_yr[,1])
plot(thrarea_1960_tag_estmov_regional_trwlfix$recruitment_yr[,1])
plot(thrarea_1960_tag_estmov_regional_NB$recruitment_yr[,1])
plot(thrarea_1960_tag_estmov_regional_NB_decadal$recruitment_yr[,1])
plot(thrarea_1960_tag_estmov_regional_NB_decadal_DM$recruitment_yr[,1])
plot(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$recruitment_yr[,1])

plot(thrarea_1960_notag_global$recruitment_yr[,2])
plot(thrarea_1960_notag_regional$recruitment_yr[,2])
plot(thrarea_1960_notag_estmov_regional$recruitment_yr[,2])
plot(thrarea_1960_notag_fenske_regional$recruitment_yr[,2])
plot(thrarea_1960_notag_fenske_sptq_regional$recruitment_yr[,2])
plot(thrarea_1960_tag_estmov_regional$recruitment_yr[,2])
plot(thrarea_1960_tag_estmov_regional_trwlfix$recruitment_yr[,2])
plot(thrarea_1960_tag_estmov_regional_NB$recruitment_yr[,2])
plot(thrarea_1960_tag_estmov_regional_NB_decadal$recruitment_yr[,2])
plot(thrarea_1960_tag_estmov_regional_NB_decadal_DM$recruitment_yr[,2])
plot(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$recruitment_yr[,2])

plot(thrarea_1960_notag_global$recruitment_yr[,3])
plot(thrarea_1960_notag_regional$recruitment_yr[,3])
plot(thrarea_1960_notag_estmov_regional$recruitment_yr[,3])
plot(thrarea_1960_notag_fenske_regional$recruitment_yr[,3])
plot(thrarea_1960_notag_fenske_sptq_regional$recruitment_yr[,3])
plot(thrarea_1960_tag_estmov_regional$recruitment_yr[,3])
plot(thrarea_1960_tag_estmov_regional_trwlfix$recruitment_yr[,3])
plot(thrarea_1960_tag_estmov_regional_NB$recruitment_yr[,3])
plot(thrarea_1960_tag_estmov_regional_NB_decadal$recruitment_yr[,3])
plot(thrarea_1960_tag_estmov_regional_NB_decadal_DM$recruitment_yr[,3])
plot(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$recruitment_yr[,3])

image(thrarea_1960_notag_global$fixed_movement_matrix[,,1])
image(thrarea_1960_notag_regional$fixed_movement_matrix[,,1])
image(thrarea_1960_notag_estmov_regional$movement_matrix[,,1])
image(thrarea_1960_notag_fenske_regional$fixed_movement_matrix[,,1])
image(thrarea_1960_notag_fenske_sptq_regional$fixed_movement_matrix[,,1])
image(thrarea_1960_tag_estmov_regional$movement_matrix[,,1])
image(thrarea_1960_tag_estmov_regional_trwlfix$movement_matrix[,,1])
image(thrarea_1960_tag_estmov_regional_NB$movement_matrix[,,1])
image(thrarea_1960_tag_estmov_regional_NB_decadal$movement_matrix[,,1])
image(thrarea_1960_tag_estmov_regional_NB_decadal_DM$movement_matrix[,,1])
image(thrarea_1960_tag_estmov_regional_NB_decadal_sptq$movement_matrix[,,1])


# 3 Area 1977 Models ------------------------------------------------------
thrarea_1977_notag_global <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_NoTagData_countrysrva/mle_report.RDS")
thrarea_1977_notag_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_NoTagData_countrysrv_regionaldevsa/mle_report.RDS")
thrarea_1977_notag_estmov_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_NoTagData_est_move_rec_srva/mle_report.RDS")
thrarea_1977_notag_fenske_regional <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_fenske_movement_countrysrva/mle_report.RDS")
thrarea_1977_notag_fenske_regional_sptq <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_fenske_movement_spt_q_countrysrva/mle_report.RDS")
thrarea_1977_tag_estmov_global <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_TagData_countrysrv_01a/mle_report.RDS")
thrarea_1977_tag_estmov_global_trwlfix <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_TagData_01_countrysrv_alta/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_TagData_reg_rec_countrysrva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_TagData_decadal_countrysrva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_TagData_01a_srva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_Model_02_srva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_Model_03_srva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_Model_04_srva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15 <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_Model_05_srva/mle_report.RDS")
thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/3-Area/1977_Model_06_srva/sd_report.RDS")

plot(thrarea_1977_notag_global$sel_fixed_f[,1])
lines(thrarea_1977_notag_regional$sel_fixed_f[,1])
lines(thrarea_1977_notag_estmov_regional$sel_fixed_f[,1])
lines(thrarea_1977_notag_fenske_regional$sel_fixed_f[,1])
lines(thrarea_1977_notag_fenske_regional_sptq$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_global$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$sel_fixed_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$sel_fixed_f[,1])

plot(thrarea_1977_notag_global$sel_fixed_f[,2])
lines(thrarea_1977_notag_regional$sel_fixed_f[,2])
lines(thrarea_1977_notag_estmov_regional$sel_fixed_f[,2])
lines(thrarea_1977_notag_fenske_regional$sel_fixed_f[,2])
lines(thrarea_1977_notag_fenske_regional_sptq$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_global$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_global_trwlfix$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$sel_fixed_f[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$sel_fixed_f[,2])

plot(thrarea_1977_notag_global$sel_trwl_f[,1])
lines(thrarea_1977_notag_regional$sel_trwl_f[,1])
lines(thrarea_1977_notag_estmov_regional$sel_trwl_f[,1])
lines(thrarea_1977_notag_fenske_regional$sel_trwl_f[,1])
lines(thrarea_1977_notag_fenske_regional_sptq$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_global$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$sel_trwl_f[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$sel_trwl_f[,1])

plot(thrarea_1977_notag_global$sel_trwl_m[,1])
lines(thrarea_1977_notag_regional$sel_trwl_m[,1])
lines(thrarea_1977_notag_estmov_regional$sel_trwl_m[,1])
lines(thrarea_1977_notag_fenske_regional$sel_trwl_m[,1])
lines(thrarea_1977_notag_fenske_regional$sel_trwl_m[,1])
lines(thrarea_1977_notag_fenske_regional_sptq$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_global$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$sel_trwl_m[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$sel_trwl_m[,1])

plot(thrarea_1977_notag_global$init_rec_dev)
plot(thrarea_1977_notag_regional$init_rec_dev)
plot(thrarea_1977_notag_estmov_regional$init_rec_dev)
plot(thrarea_1977_notag_fenske_regional$init_rec_dev)
plot(thrarea_1977_notag_fenske_regional$init_rec_dev)
plot(thrarea_1977_notag_fenske_regional_sptq$init_rec_dev)
plot(thrarea_1977_tag_estmov_global$init_rec_dev)
plot(thrarea_1977_tag_estmov_global_trwlfix$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$init_rec_dev)
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$init_rec_dev)

plot(thrarea_1977_notag_global$natage_f[,1,1])
lines(thrarea_1977_notag_regional$natage_f[,1,1])
lines(thrarea_1977_notag_estmov_regional$natage_f[,1,1])
lines(thrarea_1977_notag_fenske_regional$natage_f[,1,1])
lines(thrarea_1977_notag_fenske_regional$natage_f[,1,1])
lines(thrarea_1977_notag_fenske_regional_sptq$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_global$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$natage_f[,1,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$natage_f[,1,1])

plot(thrarea_1977_notag_global$natage_f[,2,1])
lines(thrarea_1977_notag_regional$natage_f[,2,1])
lines(thrarea_1977_notag_estmov_regional$natage_f[,2,1])
lines(thrarea_1977_notag_fenske_regional$natage_f[,2,1])
lines(thrarea_1977_notag_fenske_regional$natage_f[,2,1])
lines(thrarea_1977_notag_fenske_regional_sptq$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_global$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$natage_f[,2,1])

plot(thrarea_1977_notag_global$natage_f[,2,1])
lines(thrarea_1977_notag_regional$natage_f[,2,1])
lines(thrarea_1977_notag_estmov_regional$natage_f[,2,1])
lines(thrarea_1977_notag_fenske_regional$natage_f[,2,1])
lines(thrarea_1977_notag_fenske_regional$natage_f[,2,1])
lines(thrarea_1977_notag_fenske_regional_sptq$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_global$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$natage_f[,2,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$natage_f[,2,1])

plot(thrarea_1977_notag_global$SSB_yr[,1], ylim = c(0, 150))
lines(thrarea_1977_notag_regional$SSB_yr[,1])
lines(thrarea_1977_notag_estmov_regional$SSB_yr[,1])
lines(thrarea_1977_notag_fenske_regional$SSB_yr[,1])
lines(thrarea_1977_notag_fenske_regional$SSB_yr[,1])
lines(thrarea_1977_notag_fenske_regional_sptq$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_global$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_global_trwlfix$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$SSB_yr[,1])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$SSB_yr[,1])

plot(thrarea_1977_notag_global$SSB_yr[,2], ylim = c(0, 200))
lines(thrarea_1977_notag_regional$SSB_yr[,2])
lines(thrarea_1977_notag_estmov_regional$SSB_yr[,2])
lines(thrarea_1977_notag_fenske_regional$SSB_yr[,2])
lines(thrarea_1977_notag_fenske_regional$SSB_yr[,2])
lines(thrarea_1977_notag_fenske_regional_sptq$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_global$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_global_trwlfix$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$SSB_yr[,2])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$SSB_yr[,2])

plot(thrarea_1977_notag_global$SSB_yr[,3], ylim = c(0, 200))
lines(thrarea_1977_notag_regional$SSB_yr[,3])
lines(thrarea_1977_notag_estmov_regional$SSB_yr[,3])
lines(thrarea_1977_notag_fenske_regional$SSB_yr[,3])
lines(thrarea_1977_notag_fenske_regional$SSB_yr[,3])
lines(thrarea_1977_notag_fenske_regional_sptq$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_global$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_global_trwlfix$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$SSB_yr[,3])
lines(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$SSB_yr[,3])

plot(thrarea_1977_notag_global$recruitment_yr[,1])
plot(thrarea_1977_notag_regional$recruitment_yr[,1])
plot(thrarea_1977_notag_estmov_regional$recruitment_yr[,1])
plot(thrarea_1977_notag_fenske_regional$recruitment_yr[,1])
plot(thrarea_1977_notag_fenske_regional$recruitment_yr[,1])
plot(thrarea_1977_notag_fenske_regional_sptq$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_global$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_global_trwlfix$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$recruitment_yr[,1])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$recruitment_yr[,1])

plot(thrarea_1977_notag_global$recruitment_yr[,2])
plot(thrarea_1977_notag_regional$recruitment_yr[,2])
plot(thrarea_1977_notag_estmov_regional$recruitment_yr[,2])
plot(thrarea_1977_notag_fenske_regional$recruitment_yr[,2])
plot(thrarea_1977_notag_fenske_regional$recruitment_yr[,2])
plot(thrarea_1977_notag_fenske_regional_sptq$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_global$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_global_trwlfix$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$recruitment_yr[,2])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$recruitment_yr[,2])

plot(thrarea_1977_notag_global$recruitment_yr[,3])
plot(thrarea_1977_notag_regional$recruitment_yr[,3])
plot(thrarea_1977_notag_estmov_regional$recruitment_yr[,3])
plot(thrarea_1977_notag_fenske_regional$recruitment_yr[,3])
plot(thrarea_1977_notag_fenske_regional$recruitment_yr[,3])
plot(thrarea_1977_notag_fenske_regional_sptq$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_global$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_global_trwlfix$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$recruitment_yr[,3])
plot(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$recruitment_yr[,3])

image(thrarea_1977_notag_global$fixed_movement_matrix[,,1])
image(thrarea_1977_notag_regional$fixed_movement_matrix[,,1])
image(thrarea_1977_notag_estmov_regional$movement_matrix[,,1])
image(thrarea_1977_notag_fenske_regional$fixed_movement_matrix[,,1])
image(thrarea_1977_notag_fenske_regional_sptq$fixed_movement_matrix[,,1])
image(thrarea_1977_notag_fenske_regional_sptq$fixed_movement_matrix[,,1])
image(thrarea_1977_tag_estmov_global$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_global_trwlfix$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_same2$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15$movement_matrix[,,1])
image(thrarea_1977_tag_estmov_regional_trwlfix_decadal_NB_sum0_initdev15_sptq$movement_matrix[,,1])


# 1960 5 Area Models ------------------------------------------------------
a <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_01a_srva/mle_report.RDS")
b <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_02_srva/mle_report.RDS")
c <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_03_srva/mle_report.RDS")
d <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_04_srva/mle_report.RDS")
e <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_05_srva/mle_report.RDS")
f <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_06_srva/mle_report.RDS")
g <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_07_srva/mle_report.RDS")
h <- readRDS("/Users/matthewcheng/Desktop/Side projects/Spatial_Sablefish_Paper/Output/5-Area/Model1960_08_srva/mle_report.RDS")

